# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fdf8d45c-f523-4358-9c78-f5b9a1a0f0c1";
      fsType = "ext4";
    };
  fileSystems."/boot/efi"={
     device = "/dev/disk/by-uuid/52A7-3AB1";
     fsType = "vfat";
  };
  fileSystems."/dane" =
    { device = "/dev/disk/by-uuid/0C898D037C25A6FC";
      fsType = "ntfs";
    };
  swapDevices =
    [ { device = "/dev/disk/by-uuid/e9323f9b-e18e-4df4-af95-0be4dbc69be6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
